#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #  file:
#  #    path: /var/log/tomcat/
#  level:
#    com.imooc.LoggerTest: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.199.190/sell?characterEncoding=utf-8&useSSL=false

  jackson:
    default-property-inclusion: non_null
  main:
    allow-circular-references: true


  freemarker:
    settings:
      number_format: 0.##
  redis:
    host: 192.168.199.190
    port: 6379

server:
  servlet:
    context-path: /sell
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true

wechat:
#  mpAppId: wxd898fcb01713c658
#  mpAppSecret: 4786ff747ab75b3e26ed59b28b72d3fb
  mpAppId: wx7aef45e7ab0a62e4 #测试号appID https://mp.weixin.qq.com/debug/cgi-bin/sandboxinfo?action=showinfo&t=sandbox/index
  mpAppSecret: 4786ff747ab75b3e26ed59b28b72d3fb #测试号appsecret
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 7mdApPMfXddfWWbbP4DUaVYm2wjyh3v3
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://mytestsell.mynatapp.cc/sell/pay/notify
  templateId:
    orderStatus: KKbGxbhPpq9h4-83Ym7ap_2Udm2HjxCmjej79Ze29LQ

projecturl:
  wechatMpAuthorize: https://mytestsell.mynatapp.cc
  wechatOpenAuthorize: https://mytestsell.mynatapp.cc
  sell: https://mytestsell.mynatapp.cc




