#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #  file:
#  #    path: /var/log/tomcat/
#  level:
#    com.imooc.LoggerTest: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.199.190/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /sell
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true

wechat:
  mpAppId: wx7aef45e7ab0a62e4
  mpAppSecret: 4786ff747ab75b3e26ed59b28b72d3fb




